spring:
  application:
    name: hackathon

  datasource:
    url: jdbc:mysql://dgd.c1ukcaym4bjl.ap-northeast-2.rds.amazonaws.com:3306/gdg
    username: admin
    password: admin1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # Oauth2
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: _SSSOMaXT9P5ocmyAjCl
            client-secret: RHDP1eJaEe
            scope:
              - name
              - email
              - phoneNumber
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://43.201.161.96:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  file:
    upload:
      product:
        path: "./src/main/resources/static/productImage"

jwt:
  key: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
